# -*- coding: utf-8 -*-
"""tile

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ahjKFGiH9W2cd7HIzVZYYdHRZZly-T2-
"""

"""
Author:Team 4
Program:tile.py
Tile class
"""
class Tile:
    TILE_DICTIONARY = {"a": 1, "b": 3, "c": 3, "d": 2, "e": 1, "f": 4, "g": 2, "h": 4, 
          "i": 1, "j": 8, "k": 5, "l": 1, "m": 3, "n": 1,
          "o": 1, "p": 3,  "q": 10, "r": 1, "s": 1, "t": 1,
          "u": 1,"v": 4, "w": 4, "x": 8,  "y": 4, 
       "z": 10, "": 0}
    """Tile class"""
    def __init__(self,tile_letter, tile_score):

        if not isinstance(tile_letter,str):
            raise ValueError
        if not isinstance(tile_score, int):
            raise ValueError    
        self.tile_letter = tile_letter
        self.tile_score = TILE_DICTIONARY.get(tile_letter)
